@echo off
rem ---------------------------------------------------------------
rem This script will register each of the OPOS controls and dlls
rem contained in a folder CommonCO located in the directory where
rem this script is located.
rem 
rem The ocx and .dll files are generated by compiling the source
rem code and will be in the folder OCX/Release or OCX/Debug then
rem copying only the .ocx and the .dll files to a folder CommonCO
rem which is then zipped along with this script.
rem 
rem The applicaton RegComSvr.exe was included in the original .zip
rem file and appears to be similar in functionality to regsvr32.exe.
rem
rem NOTE: there are two versions of regsvr32.exe, one for 32 bit components
rem       and one for 64 bit components. Normally Visual Studio uses The
rem       Win32 or 32 bit platform when building.
rem ---------------------------------------------------------------
echo **
echo ** Register or Unregister OPOS Common Control Objects.
echo **   Run from a command prompt with administrator privileges,
echo **   in the directory in which this batch file is located.
echo **   There should be a folder in this directory named CommonCO
echo **   containing the OPOS .ocx and .dll files.
echo ** Formats:
echo **   Register        Register control objects.
echo **   Register -u     Unregister control objects.
echo **
echo --} Press Control-Break to exit, or
pause

@echo on

RegComSvr.exe %1 CommonCO\OPOS*.ocx CommonCO\Opos*.dll

rem ** End
